<?php
/*
 * Function used to alter the submit button value
 * If siteapikey value is set
 * Submit button value is changed to 'Update Configuration'
 */
function welcome_form_system_site_information_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
$config = \Drupal::config('system.site');  
if ( isset($form['actions']['submit']) && !empty($config->get('setapikey'))) {
   $form['actions']['submit']['#value'] = t('Update Configuration');
}
}